
package com.sap.document.sap.rfc.functions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-01-29T00:39:01.966+05:30
 * Generated source version: 3.0.2
 */

@WebFault(name = "ZMM_VENDOR_PORTAL.Exception", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public class ZMMVENDORPORTALException extends Exception {
    
    private com.sap.document.sap.rfc.functions.ZMMVENDORPORTALRfcException zmmVENDORPORTALException;

    public ZMMVENDORPORTALException() {
        super();
    }
    
    public ZMMVENDORPORTALException(String message) {
        super(message);
    }
    
    public ZMMVENDORPORTALException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZMMVENDORPORTALException(String message, com.sap.document.sap.rfc.functions.ZMMVENDORPORTALRfcException zmmVENDORPORTALException) {
        super(message);
        this.zmmVENDORPORTALException = zmmVENDORPORTALException;
    }

    public ZMMVENDORPORTALException(String message, com.sap.document.sap.rfc.functions.ZMMVENDORPORTALRfcException zmmVENDORPORTALException, Throwable cause) {
        super(message, cause);
        this.zmmVENDORPORTALException = zmmVENDORPORTALException;
    }

    public com.sap.document.sap.rfc.functions.ZMMVENDORPORTALRfcException getFaultInfo() {
        return this.zmmVENDORPORTALException;
    }
}
