package com.sap.document.sap.rfc.functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-01-29T00:39:02.106+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ZVENDOR_PORTAL", 
                  wsdlLocation = "file:/C:/Users/Lenovo/git/alkyleat/src/main/resources/vendorCreate.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZVENDORPORTAL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZVENDOR_PORTAL");
    public final static QName ZVENDORPORTAL = new QName("urn:sap-com:document:sap:rfc:functions", "ZVENDOR_PORTAL");
    public final static QName ZVENDORPORTALSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "ZVENDOR_PORTAL_soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Lenovo/git/alkyleat/src/main/resources/vendorCreate.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZVENDORPORTAL_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Lenovo/git/alkyleat/src/main/resources/vendorCreate.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZVENDORPORTAL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZVENDORPORTAL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZVENDORPORTAL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZVENDORPORTAL_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZVENDORPORTAL_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZVENDORPORTAL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ZvendorPortal
     */
    @WebEndpoint(name = "ZVENDOR_PORTAL")
    public ZvendorPortal getZVENDORPORTAL() {
        return super.getPort(ZVENDORPORTAL, ZvendorPortal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZvendorPortal
     */
    @WebEndpoint(name = "ZVENDOR_PORTAL")
    public ZvendorPortal getZVENDORPORTAL(WebServiceFeature... features) {
        return super.getPort(ZVENDORPORTAL, ZvendorPortal.class, features);
    }
    /**
     *
     * @return
     *     returns ZvendorPortal
     */
    @WebEndpoint(name = "ZVENDOR_PORTAL_soap12")
    public ZvendorPortal getZVENDORPORTALSoap12() {
        return super.getPort(ZVENDORPORTALSoap12, ZvendorPortal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZvendorPortal
     */
    @WebEndpoint(name = "ZVENDOR_PORTAL_soap12")
    public ZvendorPortal getZVENDORPORTALSoap12(WebServiceFeature... features) {
        return super.getPort(ZVENDORPORTALSoap12, ZvendorPortal.class, features);
    }

}
