package com.sap.document.sap.rfc.functions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.sap.document.sap.rfc.grn.GrnPortalObjectFactory;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-01-29T00:39:02.064+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "zvendor_portal")
@XmlSeeAlso({GrnPortalObjectFactory.class})
public interface ZvendorPortal {

    @WebMethod(operationName = "ZMM_VENDOR_PORTAL", action = "urn:sap-com:document:sap:rfc:functions:zvendor_portal:ZMM_VENDOR_PORTALRequest")
    @RequestWrapper(localName = "ZMM_VENDOR_PORTAL", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZMMVENDORPORTAL")
    @ResponseWrapper(localName = "ZMM_VENDOR_PORTALResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZMMVENDORPORTALResponse")
    public void zmmVENDORPORTAL(
        @WebParam(mode = WebParam.Mode.INOUT, name = "INPUT", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZVENDORPORTAL> input,
        @WebParam(mode = WebParam.Mode.INOUT, name = "OUTPUT", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZVENDORPORTAL> output
    ) throws ZMMVENDORPORTALException;
}
