//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.25 at 04:43:49 PM IST 
//


package com.novelerp.eat.msedcl.paymentposting;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BKTXT" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="BLDAT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="BUDAT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="CHARGES" type="{urn:sap-com:document:sap:rfc:functions}curr13.2" minOccurs="0"/&gt;
 *         &lt;element name="GATEWY_OWNR" type="{urn:sap-com:document:sap:rfc:functions}char10" minOccurs="0"/&gt;
 *         &lt;element name="PAY_TYPE" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="PRCTR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="SGTXT" type="{urn:sap-com:document:sap:rfc:functions}char50"/&gt;
 *         &lt;element name="TEXT1" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="TEXT2" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="TEXT3" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="TEXT4" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="TEXT5" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="TEXT6" type="{urn:sap-com:document:sap:rfc:functions}char50" minOccurs="0"/&gt;
 *         &lt;element name="VENDOR" type="{urn:sap-com:document:sap:rfc:functions}char10" minOccurs="0"/&gt;
 *         &lt;element name="WRBTR" type="{urn:sap-com:document:sap:rfc:functions}curr13.2"/&gt;
 *         &lt;element name="XBLNR" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="ZUONR" type="{urn:sap-com:document:sap:rfc:functions}char18" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bktxt",
    "bldat",
    "budat",
    "charges",
    "gatewyownr",
    "paytype",
    "prctr",
    "sgtxt",
    "text1",
    "text2",
    "text3",
    "text4",
    "text5",
    "text6",
    "vendor",
    "wrbtr",
    "xblnr",
    "zuonr"
})
@XmlRootElement(name = "ZFI_E_TENDER")
public class ZFIETENDER {

    @XmlElement(name = "BKTXT", required = true)
    protected String bktxt;
    @XmlElement(name = "BLDAT", required = true)
    protected String bldat;
    @XmlElement(name = "BUDAT", required = true)
    protected String budat;
    @XmlElement(name = "CHARGES")
    protected BigDecimal charges;
    @XmlElement(name = "GATEWY_OWNR")
    protected String gatewyownr;
    @XmlElement(name = "PAY_TYPE", required = true)
    protected String paytype;
    @XmlElement(name = "PRCTR", required = true)
    protected String prctr;
    @XmlElement(name = "SGTXT", required = true)
    protected String sgtxt;
    @XmlElement(name = "TEXT1")
    protected String text1;
    @XmlElement(name = "TEXT2")
    protected String text2;
    @XmlElement(name = "TEXT3")
    protected String text3;
    @XmlElement(name = "TEXT4")
    protected String text4;
    @XmlElement(name = "TEXT5")
    protected String text5;
    @XmlElement(name = "TEXT6")
    protected String text6;
    @XmlElement(name = "VENDOR")
    protected String vendor;
    @XmlElement(name = "WRBTR", required = true)
    protected BigDecimal wrbtr;
    @XmlElement(name = "XBLNR", required = true)
    protected String xblnr;
    @XmlElement(name = "ZUONR")
    protected String zuonr;

    /**
     * Gets the value of the bktxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBKTXT() {
        return bktxt;
    }

    /**
     * Sets the value of the bktxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBKTXT(String value) {
        this.bktxt = value;
    }

    /**
     * Gets the value of the bldat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBLDAT() {
        return bldat;
    }

    /**
     * Sets the value of the bldat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBLDAT(String value) {
        this.bldat = value;
    }

    /**
     * Gets the value of the budat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUDAT() {
        return budat;
    }

    /**
     * Sets the value of the budat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUDAT(String value) {
        this.budat = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCHARGES() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCHARGES(BigDecimal value) {
        this.charges = value;
    }

    /**
     * Gets the value of the gatewyownr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGATEWYOWNR() {
        return gatewyownr;
    }

    /**
     * Sets the value of the gatewyownr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGATEWYOWNR(String value) {
        this.gatewyownr = value;
    }

    /**
     * Gets the value of the paytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYTYPE() {
        return paytype;
    }

    /**
     * Sets the value of the paytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYTYPE(String value) {
        this.paytype = value;
    }

    /**
     * Gets the value of the prctr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRCTR() {
        return prctr;
    }

    /**
     * Sets the value of the prctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRCTR(String value) {
        this.prctr = value;
    }

    /**
     * Gets the value of the sgtxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSGTXT() {
        return sgtxt;
    }

    /**
     * Sets the value of the sgtxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSGTXT(String value) {
        this.sgtxt = value;
    }

    /**
     * Gets the value of the text1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT1() {
        return text1;
    }

    /**
     * Sets the value of the text1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT1(String value) {
        this.text1 = value;
    }

    /**
     * Gets the value of the text2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT2() {
        return text2;
    }

    /**
     * Sets the value of the text2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT2(String value) {
        this.text2 = value;
    }

    /**
     * Gets the value of the text3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT3() {
        return text3;
    }

    /**
     * Sets the value of the text3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT3(String value) {
        this.text3 = value;
    }

    /**
     * Gets the value of the text4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT4() {
        return text4;
    }

    /**
     * Sets the value of the text4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT4(String value) {
        this.text4 = value;
    }

    /**
     * Gets the value of the text5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT5() {
        return text5;
    }

    /**
     * Sets the value of the text5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT5(String value) {
        this.text5 = value;
    }

    /**
     * Gets the value of the text6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT6() {
        return text6;
    }

    /**
     * Sets the value of the text6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT6(String value) {
        this.text6 = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVENDOR() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVENDOR(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the wrbtr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWRBTR() {
        return wrbtr;
    }

    /**
     * Sets the value of the wrbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWRBTR(BigDecimal value) {
        this.wrbtr = value;
    }

    /**
     * Gets the value of the xblnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXBLNR() {
        return xblnr;
    }

    /**
     * Sets the value of the xblnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXBLNR(String value) {
        this.xblnr = value;
    }

    /**
     * Gets the value of the zuonr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZUONR() {
        return zuonr;
    }

    /**
     * Sets the value of the zuonr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZUONR(String value) {
        this.zuonr = value;
    }

}
