//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.25 at 04:43:49 PM IST 
//


package com.novelerp.eat.msedcl.paymentposting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LV_ALL_MSGS" type="{urn:sap-com:document:sap:rfc:functions}char255"/&gt;
 *         &lt;element name="LV_EXPORT" type="{urn:sap-com:document:sap:rfc:functions}char20"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lvallmsgs",
    "lvexport"
})
@XmlRootElement(name = "ZFI_E_TENDERResponse")
public class ZFIETENDERResponse {

    @XmlElement(name = "LV_ALL_MSGS", required = true)
    protected String lvallmsgs;
    @XmlElement(name = "LV_EXPORT", required = true)
    protected String lvexport;

    /**
     * Gets the value of the lvallmsgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLVALLMSGS() {
        return lvallmsgs;
    }

    /**
     * Sets the value of the lvallmsgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLVALLMSGS(String value) {
        this.lvallmsgs = value;
    }

    /**
     * Gets the value of the lvexport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLVEXPORT() {
        return lvexport;
    }

    /**
     * Sets the value of the lvexport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLVEXPORT(String value) {
        this.lvexport = value;
    }

}
