package com.sap.document.sap.rfc.ses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-04-13T02:07:58.427+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "zmmgrn_portal")
@XmlSeeAlso({ObjectFactory.class})
public interface ZmmgrnPortal {

    @WebMethod(operationName = "ZMM_GRN_PORTAL", action = "urn:sap-com:document:sap:rfc:functions:zmmgrn_portal:ZMM_GRN_PORTALRequest")
    @RequestWrapper(localName = "ZMM_GRN_PORTAL", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.ses.ZMMGRNPORTAL_Type")
    @ResponseWrapper(localName = "ZMM_GRN_PORTALResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.ses.ZMMGRNPORTALResponse")
    public void zmmGRNPORTAL(
        @WebParam(mode = WebParam.Mode.INOUT, name = "INPUT", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZMMGRN> input,
        @WebParam(mode = WebParam.Mode.INOUT, name = "LINEITEM", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFBAPI2017GMITEMCREATE> lineitem,
        @WebParam(mode = WebParam.Mode.INOUT, name = "OUTPUT", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFBAPI2017GMHEADRET> output,
        @WebParam(mode = WebParam.Mode.INOUT, name = "RETURN", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFBAPIRET2> _return
    );
}
