package com.sap.document.sap.rfc.ses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-04-13T02:07:58.127+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZMM_SERVICEENTRY_PORTAL")
@XmlSeeAlso({ObjectFactory.class})
public interface ZMMSERVICEENTRYPORTAL {

    @WebMethod(operationName = "ZMM_SERVICEENTRY_PORTAL", action = "urn:sap-com:document:sap:rfc:functions:ZMM_SERVICEENTRY_PORTAL:ZMM_SERVICEENTRY_PORTALRequest")
    @RequestWrapper(localName = "ZMM_SERVICEENTRY_PORTAL", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.ses.ZMMSERVICEENTRYPORTAL_Type")
    @ResponseWrapper(localName = "ZMM_SERVICEENTRY_PORTALResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.ses.ZMMSERVICEENTRYPORTALResponse")
    public void zmmSERVICEENTRYPORTAL(
        @WebParam(name = "PURCHASENO", targetNamespace = "")
        java.lang.String purchaseno,
        @WebParam(mode = WebParam.Mode.INOUT, name = "RETURN", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFBAPIRET2> _return,
        @WebParam(mode = WebParam.Mode.INOUT, name = "YENTRYSHEET", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFYENTRYSHEET> yentrysheet,
        @WebParam(mode = WebParam.Mode.INOUT, name = "YSERVICE", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFYSERVICE> yservice
    );
}
