package com.sap.document.sap.rfc.ses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-04-13T02:07:58.158+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ZMM_SERVICEENTRY_PORTAL", 
                  wsdlLocation = "file:/C:/Users/Administrator/git/alkyleat/src/main/resources/service_entry.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZMMSERVICEENTRYPORTAL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_SERVICEENTRY_PORTAL");
    public final static QName ZMMSERVICEENTRYPORTALSoap12 = new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_SERVICEENTRY_PORTAL_soap12");
    public final static QName ZMMSERVICEENTRYPORTAL = new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_SERVICEENTRY_PORTAL");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Administrator/git/alkyleat/src/main/resources/service_entry.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZMMSERVICEENTRYPORTAL_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Administrator/git/alkyleat/src/main/resources/service_entry.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZMMSERVICEENTRYPORTAL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZMMSERVICEENTRYPORTAL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMMSERVICEENTRYPORTAL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZMMSERVICEENTRYPORTAL_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZMMSERVICEENTRYPORTAL_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZMMSERVICEENTRYPORTAL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ZMMSERVICEENTRYPORTAL
     */
    @WebEndpoint(name = "ZMM_SERVICEENTRY_PORTAL_soap12")
    public ZMMSERVICEENTRYPORTAL getZMMSERVICEENTRYPORTALSoap12() {
        return super.getPort(ZMMSERVICEENTRYPORTALSoap12, ZMMSERVICEENTRYPORTAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMMSERVICEENTRYPORTAL
     */
    @WebEndpoint(name = "ZMM_SERVICEENTRY_PORTAL_soap12")
    public ZMMSERVICEENTRYPORTAL getZMMSERVICEENTRYPORTALSoap12(WebServiceFeature... features) {
        return super.getPort(ZMMSERVICEENTRYPORTALSoap12, ZMMSERVICEENTRYPORTAL.class, features);
    }
    /**
     *
     * @return
     *     returns ZMMSERVICEENTRYPORTAL
     */
    @WebEndpoint(name = "ZMM_SERVICEENTRY_PORTAL")
    public ZMMSERVICEENTRYPORTAL getZMMSERVICEENTRYPORTAL() {
        return super.getPort(ZMMSERVICEENTRYPORTAL, ZMMSERVICEENTRYPORTAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMMSERVICEENTRYPORTAL
     */
    @WebEndpoint(name = "ZMM_SERVICEENTRY_PORTAL")
    public ZMMSERVICEENTRYPORTAL getZMMSERVICEENTRYPORTAL(WebServiceFeature... features) {
        return super.getPort(ZMMSERVICEENTRYPORTAL, ZMMSERVICEENTRYPORTAL.class, features);
    }

}
