//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 12:03:59 PM IST 
//


package com.novelerp.eat.msedcl.createContract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.novelerp.eat.msedcl.craeteContract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.novelerp.eat.msedcl.craeteContract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZMMCREATECONTRACT }
     * 
     */
    public ZMMCREATECONTRACT createZMMCREATECONTRACT() {
        return new ZMMCREATECONTRACT();
    }

    /**
     * Create an instance of {@link TABLEOFZMMCONTRACTITEMCOND }
     * 
     */
    public TABLEOFZMMCONTRACTITEMCOND createTABLEOFZMMCONTRACTITEMCOND() {
        return new TABLEOFZMMCONTRACTITEMCOND();
    }

    /**
     * Create an instance of {@link TABLEOFZMMCONTRACTITEM }
     * 
     */
    public TABLEOFZMMCONTRACTITEM createTABLEOFZMMCONTRACTITEM() {
        return new TABLEOFZMMCONTRACTITEM();
    }

    /**
     * Create an instance of {@link ZMMCONTRACTHEADER }
     * 
     */
    public ZMMCONTRACTHEADER createZMMCONTRACTHEADER() {
        return new ZMMCONTRACTHEADER();
    }

    /**
     * Create an instance of {@link TABLEOFZMMCONTRACTSERVICE }
     * 
     */
    public TABLEOFZMMCONTRACTSERVICE createTABLEOFZMMCONTRACTSERVICE() {
        return new TABLEOFZMMCONTRACTSERVICE();
    }

    /**
     * Create an instance of {@link ZMMCREATECONTRACTResponse }
     * 
     */
    public ZMMCREATECONTRACTResponse createZMMCREATECONTRACTResponse() {
        return new ZMMCREATECONTRACTResponse();
    }

    /**
     * Create an instance of {@link ZMMCONTRACTITEMCOND }
     * 
     */
    public ZMMCONTRACTITEMCOND createZMMCONTRACTITEMCOND() {
        return new ZMMCONTRACTITEMCOND();
    }

    /**
     * Create an instance of {@link ZMMCONTRACTITEM }
     * 
     */
    public ZMMCONTRACTITEM createZMMCONTRACTITEM() {
        return new ZMMCONTRACTITEM();
    }

    /**
     * Create an instance of {@link ZMMCONTRACTSERVICE }
     * 
     */
    public ZMMCONTRACTSERVICE createZMMCONTRACTSERVICE() {
        return new ZMMCONTRACTSERVICE();
    }

}
