//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 12:03:59 PM IST 
//


package com.novelerp.eat.msedcl.createContract;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZMM_CONTRACT_ITEM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZMM_CONTRACT_ITEM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EBELP" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="EMATN" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="TXZ01" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="KTMNG" type="{urn:sap-com:document:sap:rfc:functions}quantum13.3"/&gt;
 *         &lt;element name="NETPR" type="{urn:sap-com:document:sap:rfc:functions}curr11.2"/&gt;
 *         &lt;element name="MWSKZ" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="BWTAR" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="MATKL" type="{urn:sap-com:document:sap:rfc:functions}char9"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZMM_CONTRACT_ITEM", propOrder = {
    "ebelp",
    "ematn",
    "txz01",
    "ktmng",
    "netpr",
    "mwskz",
    "bwtar",
    "matkl"
})
public class ZMMCONTRACTITEM {

    @XmlElement(name = "EBELP", required = true)
    protected String ebelp;
    @XmlElement(name = "EMATN", required = true)
    protected String ematn;
    @XmlElement(name = "TXZ01", required = true)
    protected String txz01;
    @XmlElement(name = "KTMNG", required = true)
    protected BigDecimal ktmng;
    @XmlElement(name = "NETPR", required = true)
    protected BigDecimal netpr;
    @XmlElement(name = "MWSKZ", required = true)
    protected String mwskz;
    @XmlElement(name = "BWTAR", required = true)
    protected String bwtar;
    @XmlElement(name = "MATKL", required = true)
    protected String matkl;

    /**
     * Gets the value of the ebelp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBELP() {
        return ebelp;
    }

    /**
     * Sets the value of the ebelp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBELP(String value) {
        this.ebelp = value;
    }

    /**
     * Gets the value of the ematn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMATN() {
        return ematn;
    }

    /**
     * Sets the value of the ematn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMATN(String value) {
        this.ematn = value;
    }

    /**
     * Gets the value of the txz01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXZ01() {
        return txz01;
    }

    /**
     * Sets the value of the txz01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXZ01(String value) {
        this.txz01 = value;
    }

    /**
     * Gets the value of the ktmng property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKTMNG() {
        return ktmng;
    }

    /**
     * Sets the value of the ktmng property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKTMNG(BigDecimal value) {
        this.ktmng = value;
    }

    /**
     * Gets the value of the netpr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNETPR() {
        return netpr;
    }

    /**
     * Sets the value of the netpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNETPR(BigDecimal value) {
        this.netpr = value;
    }

    /**
     * Gets the value of the mwskz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWSKZ() {
        return mwskz;
    }

    /**
     * Sets the value of the mwskz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWSKZ(String value) {
        this.mwskz = value;
    }

    /**
     * Gets the value of the bwtar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBWTAR() {
        return bwtar;
    }

    /**
     * Sets the value of the bwtar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBWTAR(String value) {
        this.bwtar = value;
    }

    /**
     * Gets the value of the matkl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATKL() {
        return matkl;
    }

    /**
     * Sets the value of the matkl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATKL(String value) {
        this.matkl = value;
    }

}
