//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 12:03:59 PM IST 
//


package com.novelerp.eat.msedcl.createContract;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZMM_CONTRACT_ITEM_COND complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZMM_CONTRACT_ITEM_COND"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EBELP" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="SER_EBELP" type="{urn:sap-com:document:sap:rfc:functions}numeric5"/&gt;
 *         &lt;element name="KSCHL" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="KBETR" type="{urn:sap-com:document:sap:rfc:functions}curr11.2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZMM_CONTRACT_ITEM_COND", propOrder = {
    "ebelp",
    "serebelp",
    "kschl",
    "kbetr"
})
public class ZMMCONTRACTITEMCOND {

    @XmlElement(name = "EBELP", required = true)
    protected String ebelp;
    @XmlElement(name = "SER_EBELP", required = true)
    protected String serebelp;
    @XmlElement(name = "KSCHL", required = true)
    protected String kschl;
    @XmlElement(name = "KBETR", required = true)
    protected BigDecimal kbetr;

    /**
     * Gets the value of the ebelp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBELP() {
        return ebelp;
    }

    /**
     * Sets the value of the ebelp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBELP(String value) {
        this.ebelp = value;
    }

    /**
     * Gets the value of the serebelp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEREBELP() {
        return serebelp;
    }

    /**
     * Sets the value of the serebelp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEREBELP(String value) {
        this.serebelp = value;
    }

    /**
     * Gets the value of the kschl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKSCHL() {
        return kschl;
    }

    /**
     * Sets the value of the kschl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKSCHL(String value) {
        this.kschl = value;
    }

    /**
     * Gets the value of the kbetr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKBETR() {
        return kbetr;
    }

    /**
     * Sets the value of the kbetr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKBETR(BigDecimal value) {
        this.kbetr = value;
    }

}
