//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.28 at 12:03:59 PM IST 
//


package com.novelerp.eat.msedcl.createContract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CONTRACT_CONDITION" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZMM_CONTRACT_ITEM_COND" minOccurs="0"/&gt;
 *         &lt;element name="CONTRACT_ITEM" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZMM_CONTRACT_ITEM" minOccurs="0"/&gt;
 *         &lt;element name="GS_CONTRACT_HEADER" type="{urn:sap-com:document:sap:rfc:functions}ZMM_CONTRACT_HEADER"/&gt;
 *         &lt;element name="VAL_CONTRACT_SERVICE" type="{urn:sap-com:document:sap:rfc:functions}TABLE_OF_ZMM_CONTRACT_SERVICE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contractcondition",
    "contractitem",
    "gscontractheader",
    "valcontractservice"
})
@XmlRootElement(name = "ZMM_CREATE_CONTRACT")
public class ZMMCREATECONTRACT {

    @XmlElement(name = "CONTRACT_CONDITION")
    protected TABLEOFZMMCONTRACTITEMCOND contractcondition;
    @XmlElement(name = "CONTRACT_ITEM")
    protected TABLEOFZMMCONTRACTITEM contractitem;
    @XmlElement(name = "GS_CONTRACT_HEADER", required = true)
    protected ZMMCONTRACTHEADER gscontractheader;
    @XmlElement(name = "VAL_CONTRACT_SERVICE")
    protected TABLEOFZMMCONTRACTSERVICE valcontractservice;

    /**
     * Gets the value of the contractcondition property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZMMCONTRACTITEMCOND }
     *     
     */
    public TABLEOFZMMCONTRACTITEMCOND getCONTRACTCONDITION() {
        return contractcondition;
    }

    /**
     * Sets the value of the contractcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZMMCONTRACTITEMCOND }
     *     
     */
    public void setCONTRACTCONDITION(TABLEOFZMMCONTRACTITEMCOND value) {
        this.contractcondition = value;
    }

    /**
     * Gets the value of the contractitem property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZMMCONTRACTITEM }
     *     
     */
    public TABLEOFZMMCONTRACTITEM getCONTRACTITEM() {
        return contractitem;
    }

    /**
     * Sets the value of the contractitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZMMCONTRACTITEM }
     *     
     */
    public void setCONTRACTITEM(TABLEOFZMMCONTRACTITEM value) {
        this.contractitem = value;
    }

    /**
     * Gets the value of the gscontractheader property.
     * 
     * @return
     *     possible object is
     *     {@link ZMMCONTRACTHEADER }
     *     
     */
    public ZMMCONTRACTHEADER getGSCONTRACTHEADER() {
        return gscontractheader;
    }

    /**
     * Sets the value of the gscontractheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZMMCONTRACTHEADER }
     *     
     */
    public void setGSCONTRACTHEADER(ZMMCONTRACTHEADER value) {
        this.gscontractheader = value;
    }

    /**
     * Gets the value of the valcontractservice property.
     * 
     * @return
     *     possible object is
     *     {@link TABLEOFZMMCONTRACTSERVICE }
     *     
     */
    public TABLEOFZMMCONTRACTSERVICE getVALCONTRACTSERVICE() {
        return valcontractservice;
    }

    /**
     * Sets the value of the valcontractservice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TABLEOFZMMCONTRACTSERVICE }
     *     
     */
    public void setVALCONTRACTSERVICE(TABLEOFZMMCONTRACTSERVICE value) {
        this.valcontractservice = value;
    }

}
