/*//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.27 at 05:48:50 PM IST 
//


package com.novelerp.eat.msedcl.sap;


import javax.xml.bind.annotation.XmlRegistry;

import org.springframework.stereotype.Component;


*//**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.novelerp.eat.msedcl.sap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 *//*
@XmlRegistry
@Component
public class ObjectFactory {


    *//**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.novelerp.eat.msedcl.sap
     * 
     *//*
    public ObjectFactory() {
    }

    *//**
     * Create an instance of {@link ZVENDORCREATE }
     * 
     *//*
    public ZVENDORCREATE createZVENDORCREATE0718() {
        return new ZVENDORCREATE();
    }

    *//**
     * Create an instance of {@link ZVENDORCREATEResponse }
     * 
     *//*
    public ZVENDORCREATEResponse createZVENDORCREATE0718Response() {
        return new ZVENDORCREATEResponse();
    }

}
*/