//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 03:33:30 PM IST 
//


package com.novelerp.eat.msedcl.sap;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TABLE_OF_ZVEND_MAST_WTHOLDTAX_STRUCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TABLE_OF_ZVEND_MAST_WTHOLDTAX_STRUCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" type="{urn:sap-com:document:sap:rfc:functions}ZVEND_MAST_WTHOLDTAX_STRUCT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TABLE_OF_ZVEND_MAST_WTHOLDTAX_STRUCT", propOrder = {
    "item"
})
public class TABLEOFZVENDMASTWTHOLDTAXSTRUCT {

    protected List<ZVENDMASTWTHOLDTAXSTRUCT> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZVENDMASTWTHOLDTAXSTRUCT }
     * 
     * 
     */
    public List<ZVENDMASTWTHOLDTAXSTRUCT> getItem() {
        if (item == null) {
            item = new ArrayList<ZVENDMASTWTHOLDTAXSTRUCT>();
        }
        return this.item;
    }

}
