//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.27 at 05:48:50 PM IST 
//


package com.novelerp.eat.msedcl.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AKONT" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="BANKA" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="BANKL_01" type="{urn:sap-com:document:sap:rfc:functions}char15"/&gt;
 *         &lt;element name="BANKN_01" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="BRNCH" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="J_1IPANNO" type="{urn:sap-com:document:sap:rfc:functions}char40"/&gt;
 *         &lt;element name="KOINH_01" type="{urn:sap-com:document:sap:rfc:functions}char60"/&gt;
 *         &lt;element name="KTOKK" type="{urn:sap-com:document:sap:rfc:functions}char4"/&gt;
 *         &lt;element name="LAND1" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="NAME1" type="{urn:sap-com:document:sap:rfc:functions}char35" minOccurs="0"/&gt;
 *         &lt;element name="ORT01" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="ORT02" type="{urn:sap-com:document:sap:rfc:functions}char25"/&gt;
 *         &lt;element name="PROVZ" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="PSTLZ" type="{urn:sap-com:document:sap:rfc:functions}char10"/&gt;
 *         &lt;element name="REGIO" type="{urn:sap-com:document:sap:rfc:functions}char3"/&gt;
 *         &lt;element name="STCD1" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="STCD3" type="{urn:sap-com:document:sap:rfc:functions}char18"/&gt;
 *         &lt;element name="STRAS" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="TELF1" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="TELF2" type="{urn:sap-com:document:sap:rfc:functions}char16"/&gt;
 *         &lt;element name="TELX1" type="{urn:sap-com:document:sap:rfc:functions}char30"/&gt;
 *         &lt;element name="VEN_CLASS" type="{urn:sap-com:document:sap:rfc:functions}char1"/&gt;
 *         &lt;element name="WITHT_02" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WT_WITHCD_01" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WT_WITHCD_02" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "akont",
    "banka",
    "bankl01",
    "bankn01",
    "brnch",
    "j1IPANNO",
    "koinh01",
    "ktokk",
    "land1",
    "name1",
    "ort01",
    "ort02",
    "provz",
    "pstlz",
    "regio",
    "stcd1",
    "stcd3",
    "stras",
    "telf1",
    "telf2",
    "telx1",
    "venclass",
    "witht02",
    "wtwithcd01",
    "wtwithcd02"
})
@XmlRootElement(name = "ZVENDOR_CREATE_0718")
public class ZVENDORCREATE {

    @XmlElement(name = "AKONT", required = true)
    protected String akont;
    @XmlElement(name = "BANKA", required = true)
    protected String banka;
    @XmlElement(name = "BANKL_01", required = true)
    protected String bankl01;
    @XmlElement(name = "BANKN_01", required = true)
    protected String bankn01;
    @XmlElement(name = "BRNCH", required = true)
    protected String brnch;
    @XmlElement(name = "J_1IPANNO", required = true)
    protected String j1IPANNO;
    @XmlElement(name = "KOINH_01", required = true)
    protected String koinh01;
    @XmlElement(name = "KTOKK", required = true)
    protected String ktokk;
    @XmlElement(name = "LAND1", required = true)
    protected String land1;
    @XmlElement(name = "NAME1")
    protected String name1;
    @XmlElement(name = "ORT01", required = true)
    protected String ort01;
    @XmlElement(name = "ORT02", required = true)
    protected String ort02;
    @XmlElement(name = "PROVZ", required = true)
    protected String provz;
    @XmlElement(name = "PSTLZ", required = true)
    protected String pstlz;
    @XmlElement(name = "REGIO", required = true)
    protected String regio;
    @XmlElement(name = "STCD1", required = true)
    protected String stcd1;
    @XmlElement(name = "STCD3", required = true)
    protected String stcd3;
    @XmlElement(name = "STRAS", required = true)
    protected String stras;
    @XmlElement(name = "TELF1", required = true)
    protected String telf1;
    @XmlElement(name = "TELF2", required = true)
    protected String telf2;
    @XmlElement(name = "TELX1", required = true)
    protected String telx1;
    @XmlElement(name = "VEN_CLASS", required = true)
    protected String venclass;
    @XmlElement(name = "WITHT_02", required = true)
    protected String witht02;
    @XmlElement(name = "WT_WITHCD_01", required = true)
    protected String wtwithcd01;
    @XmlElement(name = "WT_WITHCD_02", required = true)
    protected String wtwithcd02;

    /**
     * Gets the value of the akont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAKONT() {
        return akont;
    }

    /**
     * Sets the value of the akont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAKONT(String value) {
        this.akont = value;
    }

    /**
     * Gets the value of the banka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKA() {
        return banka;
    }

    /**
     * Sets the value of the banka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKA(String value) {
        this.banka = value;
    }

    /**
     * Gets the value of the bankl01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKL01() {
        return bankl01;
    }

    /**
     * Sets the value of the bankl01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKL01(String value) {
        this.bankl01 = value;
    }

    /**
     * Gets the value of the bankn01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKN01() {
        return bankn01;
    }

    /**
     * Sets the value of the bankn01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKN01(String value) {
        this.bankn01 = value;
    }

    /**
     * Gets the value of the brnch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRNCH() {
        return brnch;
    }

    /**
     * Sets the value of the brnch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRNCH(String value) {
        this.brnch = value;
    }

    /**
     * Gets the value of the j1IPANNO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJ1IPANNO() {
        return j1IPANNO;
    }

    /**
     * Sets the value of the j1IPANNO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJ1IPANNO(String value) {
        this.j1IPANNO = value;
    }

    /**
     * Gets the value of the koinh01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOINH01() {
        return koinh01;
    }

    /**
     * Sets the value of the koinh01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOINH01(String value) {
        this.koinh01 = value;
    }

    /**
     * Gets the value of the ktokk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKTOKK() {
        return ktokk;
    }

    /**
     * Sets the value of the ktokk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKTOKK(String value) {
        this.ktokk = value;
    }

    /**
     * Gets the value of the land1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLAND1() {
        return land1;
    }

    /**
     * Sets the value of the land1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLAND1(String value) {
        this.land1 = value;
    }

    /**
     * Gets the value of the name1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME1() {
        return name1;
    }

    /**
     * Sets the value of the name1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME1(String value) {
        this.name1 = value;
    }

    /**
     * Gets the value of the ort01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORT01() {
        return ort01;
    }

    /**
     * Sets the value of the ort01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORT01(String value) {
        this.ort01 = value;
    }

    /**
     * Gets the value of the ort02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORT02() {
        return ort02;
    }

    /**
     * Sets the value of the ort02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORT02(String value) {
        this.ort02 = value;
    }

    /**
     * Gets the value of the provz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROVZ() {
        return provz;
    }

    /**
     * Sets the value of the provz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROVZ(String value) {
        this.provz = value;
    }

    /**
     * Gets the value of the pstlz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSTLZ() {
        return pstlz;
    }

    /**
     * Sets the value of the pstlz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSTLZ(String value) {
        this.pstlz = value;
    }

    /**
     * Gets the value of the regio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGIO() {
        return regio;
    }

    /**
     * Sets the value of the regio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGIO(String value) {
        this.regio = value;
    }

    /**
     * Gets the value of the stcd1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTCD1() {
        return stcd1;
    }

    /**
     * Sets the value of the stcd1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTCD1(String value) {
        this.stcd1 = value;
    }

    /**
     * Gets the value of the stcd3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTCD3() {
        return stcd3;
    }

    /**
     * Sets the value of the stcd3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTCD3(String value) {
        this.stcd3 = value;
    }

    /**
     * Gets the value of the stras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRAS() {
        return stras;
    }

    /**
     * Sets the value of the stras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRAS(String value) {
        this.stras = value;
    }

    /**
     * Gets the value of the telf1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTELF1() {
        return telf1;
    }

    /**
     * Sets the value of the telf1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTELF1(String value) {
        this.telf1 = value;
    }

    /**
     * Gets the value of the telf2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTELF2() {
        return telf2;
    }

    /**
     * Sets the value of the telf2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTELF2(String value) {
        this.telf2 = value;
    }

    /**
     * Gets the value of the telx1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTELX1() {
        return telx1;
    }

    /**
     * Sets the value of the telx1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTELX1(String value) {
        this.telx1 = value;
    }

    /**
     * Gets the value of the venclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVENCLASS() {
        return venclass;
    }

    /**
     * Sets the value of the venclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVENCLASS(String value) {
        this.venclass = value;
    }

    /**
     * Gets the value of the witht02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT02() {
        return witht02;
    }

    /**
     * Sets the value of the witht02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT02(String value) {
        this.witht02 = value;
    }

    /**
     * Gets the value of the wtwithcd01 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWTWITHCD01() {
        return wtwithcd01;
    }

    /**
     * Sets the value of the wtwithcd01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWTWITHCD01(String value) {
        this.wtwithcd01 = value;
    }

    /**
     * Gets the value of the wtwithcd02 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWTWITHCD02() {
        return wtwithcd02;
    }

    /**
     * Sets the value of the wtwithcd02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWTWITHCD02(String value) {
        this.wtwithcd02 = value;
    }

}
