//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 03:33:30 PM IST 
//


package com.novelerp.eat.msedcl.sap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZVEND_MAST_WTHOLDTAX_STRUCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZVEND_MAST_WTHOLDTAX_STRUCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WITHT1" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT2" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT3" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT4" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT5" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT6" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *         &lt;element name="WITHT7" type="{urn:sap-com:document:sap:rfc:functions}char2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZVEND_MAST_WTHOLDTAX_STRUCT", propOrder = {
    "witht1",
    "witht2",
    "witht3",
    "witht4",
    "witht5",
    "witht6",
    "witht7"
})
public class ZVENDMASTWTHOLDTAXSTRUCT {

    @XmlElement(name = "WITHT1", required = true)
    protected String witht1;
    @XmlElement(name = "WITHT2", required = true)
    protected String witht2;
    @XmlElement(name = "WITHT3", required = true)
    protected String witht3;
    @XmlElement(name = "WITHT4", required = true)
    protected String witht4;
    @XmlElement(name = "WITHT5", required = true)
    protected String witht5;
    @XmlElement(name = "WITHT6", required = true)
    protected String witht6;
    @XmlElement(name = "WITHT7", required = true)
    protected String witht7;

    /**
     * Gets the value of the witht1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT1() {
        return witht1;
    }

    /**
     * Sets the value of the witht1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT1(String value) {
        this.witht1 = value;
    }

    /**
     * Gets the value of the witht2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT2() {
        return witht2;
    }

    /**
     * Sets the value of the witht2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT2(String value) {
        this.witht2 = value;
    }

    /**
     * Gets the value of the witht3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT3() {
        return witht3;
    }

    /**
     * Sets the value of the witht3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT3(String value) {
        this.witht3 = value;
    }

    /**
     * Gets the value of the witht4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT4() {
        return witht4;
    }

    /**
     * Sets the value of the witht4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT4(String value) {
        this.witht4 = value;
    }

    /**
     * Gets the value of the witht5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT5() {
        return witht5;
    }

    /**
     * Sets the value of the witht5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT5(String value) {
        this.witht5 = value;
    }

    /**
     * Gets the value of the witht6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT6() {
        return witht6;
    }

    /**
     * Sets the value of the witht6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT6(String value) {
        this.witht6 = value;
    }

    /**
     * Gets the value of the witht7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHT7() {
        return witht7;
    }

    /**
     * Sets the value of the witht7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHT7(String value) {
        this.witht7 = value;
    }

}
